# Generated by Django 5.0.2 on 2024-02-16 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_products_category_remove_products_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='tot_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
